build.gradle
gradle.properties

1. corrected the group name in build.gradle file
2. removed unused dependencies
3. changed version to 0.0.60

fixed the failing build

---

README.md

Updated readme to fix the typo for test execution in iOS platform.

update readme for running tests on iOS

---

src/main/java/com/znsio/e2e/runner/Runner.java
src/main/java/com/znsio/e2e/tools/Drivers.java

- added a method to check availability of apk file in the mentioned path 
- spell check for a method and variable

added a check to validate availability of apk file in the mentioned path

---

src/main/java/com/znsio/e2e/tools/Driver.java
src/main/java/com/znsio/e2e/tools/Drivers.java

commented the terminateApp method in the closeAppOnDevice

File upload

---

README.md
src/main/java/com/znsio/e2e/runner/Runner.java
src/main/java/com/znsio/e2e/runner/Setup.java
src/main/java/com/znsio/e2e/tools/Driver.java
src/main/java/com/znsio/e2e/tools/Drivers.java

also, added a chrome option for safe browsing

added tag for multiuser on windows platform + flag to allow insecure certs

---

docker-compose.yml
getAvailablePort.sh
wait_for_containers_to_be_up.sh

1. Added the docker-compose.yml file to dockerize the test environment(chrome, selenium hub and appium server)
2. Added a shell script to pick the available ports for selenium grid and appium
3. Added a shell script to wait for the appium server and selegium grid to be up an running

Dokerized teswiz

---

README.md
build.gradle
src/main/java/com/znsio/e2e/entities/APPLITOOLS.java
src/main/java/com/znsio/e2e/entities/TEST_CONTEXT.java
src/main/java/com/znsio/e2e/tools/Visual.java
src/test/java/com/znsio/e2e/steps/RunTestCukes.java
src/test/resources/com/znsio/e2e/features/configs/applitools_config.json
src/test/resources/com/znsio/e2e/features/login.feature

Added Applitools UFG support with default fallback configuration

Applitools UFG support

---

src/main/java/com/znsio/e2e/tools/Drivers.java

added geolocation to enable geolocation services for chrome

added geolocation to enable geolocation services for chrome

---

src/main/java/com/znsio/e2e/tools/Driver.java

Added scrollToBottom and scrollTillElementInView method in driver class for Web Scrolling

Added scrollToBottom and scrollTillElementInView method

---

src/main/java/com/znsio/e2e/tools/Drivers.java
src/test/resources/com/znsio/e2e/features/configs/browser_config.json

Added createSafariDriver method in Drivers.java for safari browser support

Added createSafariDriver method for safari browser support

---

src/main/java/com/znsio/e2e/tools/Driver.java

Updated method waitTillElementIsPresent 
Added new method 'waitTillElementIsVisible' in Driver class

Updated waitTillElementIsPresent + added new method 'waitTillElementIsVisible' to handle dynamic wait time 

---

src/main/java/com/znsio/e2e/exceptions/VisualTestSetupException.java
src/main/java/com/znsio/e2e/tools/Visual.java

Added New VisualTestSetupException and Updated Visual.java.

Visual Test Setup exception 

---

src/main/java/com/znsio/e2e/tools/Driver.java

Updated waitTillPresenceOfAllElements and added waitTillVisibilityOfAllElements method in Driver.java

Updated and added a method in Driver.java

---

src/main/java/com/znsio/teswiz/runner/CustomReports.java

added "file://" line to make cucumber report path as hyperlink in CustomReports.java

added "file://" line to make cucumber report path as hyperlink

---

src/main/java/com/znsio/teswiz/runner/Driver.java

created a scroll function that works for mobile & tablet. which does normal scroll & scrolls the inner window

Feature: Added a function to scroll into dynamic layer/inner window

---

build.gradle
src/main/java/com/znsio/teswiz/runner/BrowserDriverManager.java

added chrome options argument ("--disable-gpu")

added- chrome options for selenium timeout issue test

---

src/main/java/com/znsio/teswiz/runner/Driver.java
src/test/java/com/znsio/teswiz/businessLayer/vodqa/VodqaBL.java
src/test/java/com/znsio/teswiz/screen/android/vodqa/VodqaScreenAndroid.java
src/test/java/com/znsio/teswiz/screen/vodqa/VodqaScreen.java
src/test/java/com/znsio/teswiz/steps/VodQASteps.java
src/test/resources/com/znsio/teswiz/features/vodqa.feature

Implemented run app in background funtionality
Updated driver class method "putAppInBackground"
Validated by implmenting test in vodqa.feature file

Backmerging from appium:2.0

---

src/main/java/com/znsio/teswiz/entities/Direction.java
src/main/java/com/znsio/teswiz/runner/Driver.java
src/test/java/com/znsio/teswiz/businessLayer/vodqa/VodqaBL.java
src/test/java/com/znsio/teswiz/screen/android/vodqa/VodqaScreenAndroid.java
src/test/java/com/znsio/teswiz/screen/vodqa/VodqaScreen.java
src/test/java/com/znsio/teswiz/steps/VodQASteps.java
src/test/resources/com/znsio/teswiz/features/vodqa.feature

1. Removed deprecated objects like PerformsTouchActions from scrollInDynamicLayer()
2. Corrected fromPoint and toPoint scroll in scroll() functionality
3. Added a scenario to validate scrollInDynamicLayer()

Appium2.0: Scroll in dynamic layer implementation and addition of a test scenario

---

src/test/java/com/znsio/teswiz/businessLayer/vodqa/VodqaBL.java
src/test/java/com/znsio/teswiz/screen/android/vodqa/VodqaScreenAndroid.java
src/test/java/com/znsio/teswiz/screen/vodqa/VodqaScreen.java
src/test/java/com/znsio/teswiz/steps/VodQASteps.java
src/test/resources/com/znsio/teswiz/features/vodqa.feature

Removed redundant code from test scenarios

Appium2.0: Removed redundant methods from vodQa scenarios

---

README.md
docs/GettingStartedUsingTeswiz-README.md

- Updated Readme.md file with changes made in v0.0.80
- updated prerequisites in getting started documentation

Updating teswiz documentation for v0.0.80

---

src/main/java/com/znsio/teswiz/runner/BrowserDriverManager.java

Did the following tasks:
1. Resolved TODO loggingPrefs for firefox by modifying setCapability().
2. Added setLogLevel(), loggingPrefs for createChromeDriver.
3. Added loggingPrefs for createFirefoxDriver.

Resolved TODO loggingPrefs for firefox.

---

README.md
src/main/java/com/znsio/teswiz/runner/Driver.java

This method is to set an attribute value for a given element on the page. It takes three arguments:
1. `element` whose attributes needs to be changed
2. `attribute` which attribute of the element needs to be changed like class, name, value, id
3. `value` which will be updated for the chosen attribute

Implemented setAttributeValue method in driver class

---

README.md
docs/BrowserStackLocal_README.md

1. updated documentation & readme file for Teswiz v0.0.81

[Teswiz-Upgrade] Updated Documentation & Readme file

---

build.gradle

Have added all the jacoco implementation in build.gradle file
along with comments - indicating the implementation tried

Jacoco changes in teswiz

---

src/test/java/com/znsio/teswiz/screen/android/ajio/SearchScreenAndroid.java

Updating access modifier to private

Changing access modifier from public to private

---

src/test/java/com/znsio/teswiz/screen/android/ajio/ProductScreenAndroid.java
src/test/java/com/znsio/teswiz/screen/android/ajio/SearchScreenAndroid.java

Fixing the imageSearch scenario in ajio test - by updating the product layout id

Fixing imageSearch scenario in ajio test

---

src/main/java/com/znsio/teswiz/runner/Driver.java

**Problem Statement:** The current scrollToAnElementByText(String text) is failing in the middle of the scroll due to limited scroll capability
====== 
Added a new method scrollToAnElementByText(String text, int maxSwipes) which takes 2 parameters.
1. STRING: text to search
2.  INT: maxSwipes
2nd parameter, int maxSwipes, gives the control to the user to scroll the number of times in the current page.

Added overloaded scrollToAnElementByText() to get control over number of times to scroll

---

src/main/java/com/znsio/teswiz/entities/TEST_CONTEXT.java
src/main/java/com/znsio/teswiz/tools/Heartbeat.java
src/test/java/com/znsio/teswiz/businessLayer/jiomeet/InAMeetingBL.java
src/test/java/com/znsio/teswiz/steps/JioMeetSteps.java
src/test/java/com/znsio/teswiz/steps/RunTestCukes.java
src/test/resources/com/znsio/teswiz/features/jiomeet.feature

Added code to reproduce multithreading issue

Heartbeat Issue with multithreading

---

README.md
docs/HardGate.md
src/main/java/com/znsio/teswiz/tools/IPAddress.java

- updated the HardGate.md doc with examples
- updated access modifiers for a class IPAddress in com.znsio.teswiz.tools

Updated Hard Gate Feature Readme file

---

src/main/java/com/znsio/teswiz/runner/Driver.java

Added methods in the driver class to set and retrieve clipboard text as these methods need to be repeatedly used in our app automation.

Added methods in driver class to set and retrieve clipboard text
